# Generated by Django 4.1.5 on 2023-03-03 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('name', models.CharField(help_text='Определяет название пункта меню', max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(help_text='Определяет slug пункта меню', max_length=100, unique=True, verbose_name='URL')),
                ('parent', models.ForeignKey(blank=True, help_text='Определяет, к какому разделу принадлежит данный пункт меню. Если значение не указано, то пункт считается заглавным.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.menu', verbose_name='Родитель')),
            ],
        ),
    ]
